version: "3"

services:
  server:
    build: ./backend
    volumes:
      - ./backend:/usr/app/backend
      - /usr/app/backend/node_modules
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    container_name: backend
