version: "3"

services:
  backend:
    build: ./backend
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/gofundleaf?schema=public
      - GOOGLE_CLIENT_ID=756518914212-1vskm0087acrsii1ihq3r74hg8i24som.apps.googleusercontent.com
    ports:
      - "8080:8080"
    container_name: backend
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    container_name: db
